# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.BigIntegerField()),
                ('customer_address', models.CharField(max_length=1000)),
                ('measurements', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bill', django.contrib.postgres.fields.jsonb.JSONField()),
                ('delivery_date', models.DateTimeField()),
                ('text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tailor_order',
            },
        ),
    ]
