# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20161125_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
