# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
    ]
